name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v2

      - name: Flutterのセットアップ
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          
      - name: Flutterキャッシュ削除
        run: flutter clean && rm -rf ~/.pub-cache

      - name: Fix Flutter SDK folder permission
        run: git config --global --add safe.directory /tmp/flutter/

      - name: 依存関係の取得
        run: flutter pub get

      - name: Webビルド
        run: flutter build web --release

      - name: アーティファクトのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

      - name: Firebase CLI のセットアップ
        run: npm install -g firebase-tools

      - name: Firebase 認証情報を設定
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > firebase-key.json

      - name: Firebase Hosting デプロイ
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
        env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
